### PR TITLE
Ability to add custom metadata to S3 objects

### LINKED ISSUE #8: Metadata with uploads
It would be good to get a way to set metadata with uploads, as per http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#UserMetadata

@samoconnor thoughts on the best way to implement this?

### PR DESCRIPTION
**Pull request by aviks**
Fix #8

Usage as follows: 

```julia
s3_put(env, "bucket", "file_name", "File Contents", metadata=Dict{String, String}("custom"=>"value"))
```

### CODE REVIEW

**Comment by aviks** [comment]
@samoconnor do you know why the tests failed? seems like a connection error to S3.

**Comment by jingpengw** [comment]
the osx build passed, only the linux build failed.
https://travis-ci.org/samoconnor/AWSS3.jl/builds/225821350
@samoconnor could you take a look and merge this PR? 
I need this function, just created a PR https://github.com/samoconnor/AWSS3.jl/pull/10
but just find that this PR is more general.

**Comment by aviks** [comment]
Ping?

**Comment by samoconnor** [comment]
Thanks @aviks!

**Comment by samoconnor** [comment]
See test case and simplification of Dict construction in  0e8438307f72c3ee3f6e552e9b3af0325a90e40c

**Comment by aviks** [comment]
Thanks!

**Comment by jingpengw** [comment]
great, thanks!

**Comment by jingpengw** [comment]
@samoconnor I see a lot of updates in both AWSS3 and AWSCore, would you like to make a new release to METADATA?

**Comment by samoconnor** [comment]
Hi @jingpengw, I plan to do that soon, but I've got a few more planned updates to get through fist.

**Pull request merged**
