### PR TITLE
Replace LightXML with EzXML

### PR DESCRIPTION
**Pull request by ararslan**
Followup from #30. @samoconnor

### CODE REVIEW

**Comment by ararslan** [comment]
Seems that it's the same issue with credentials not being available.

**Comment by samoconnor** [comment]
I'm testing this locally.
There is another issue caused by places in AWSCore that do `String(::Vector{UInt8})` which in 0.7 results in the Vector being truncated to zero length :(

**Comment by ararslan** [comment]
Yeah, because the string takes ownership of the underlying data in the array upon construction. If you can point me to particular instances where it's causing a problem I can submit a PR. For example, if you're getting errors, the backtrace would be helpful.

**Comment by samoconnor** [comment]
https://github.com/JuliaCloud/AWSCore.jl/commit/fda9819a6715e66c97bf1b5c6592a4bd092df981

**Comment by samoconnor** [comment]
I'm now getting as far as `ERROR: LoadError: UndefVarError: BufferStream not defined`

**Comment by samoconnor** [comment]
https://github.com/JuliaCloud/AWSCore.jl/commit/5d173bd159d8e6748c7873ff02fe36cd4c3e1d13

**Comment by ararslan** [comment]
So I take it things are all good now? :D

**Comment by samoconnor** [comment]
The AWSS3 tests passed on my machine with the resent AWSCore commits.

This is looking good too: https://travis-ci.org/samoconnor/AWSS3.jl/jobs/410592595

The `String` thing makes me concerned that there may be other 0.7 change bugs lurking in `AWSCore`. I feel like it needs a code review against a list of things that may break in 0.7.

**Comment by samoconnor** [comment]
Fair enough.
I've just tried out AWSSQS.jl and AWSSNS.jl on my local machine.
Aside from the patch below for the runtest.jl file and a dep warnings, the tests pass.

```patch
diff --git a/test/runtests.jl b/test/runtests.jl
index 31da8b4..3c9d4f2 100755
--- a/test/runtests.jl
+++ b/test/runtests.jl
@@ -5,6 +5,7 @@
 #==============================================================================#


+using AWSCore
 using AWSSQS
 using AWSSNS
 using Retry
```

I'm happy to accept PRs for AWSSQS.jl and AWSSNS.jl to drop 0.6 and fix the deprecations.
If we can get AWSCore, AWSS3, AWSSQS and AWSSNS all passing CI I'll tag them all.

**Comment by ararslan** [comment]
Sounds fantastic. Thanks!

**Pull request merged**
